### ISSUE TITLE
Feature and/or Status request: v10 compatibility?

### ISSUE THREAD

**Issue by esheyw** [jtracey/journal-backlinks#10]
I understand its likely a pretty big lift to get done, just want to know if I should be holding my breath on this mod, metaphorically speaking. Love the functionality, would hate to lose it 🙂

**Comment by jtracey** [comment]
So far, I've been using my only, live deployment for development too. I'm ~3/4ths of the way through a campaign, so I don't want to update that instance now. I do want to bump the support on this extension to v10 before that campaign finishes though, so it's mostly just a matter of finding a weekend for me get a development v10 instance running in parallel, then porting and testing. I.e., I don't quite know *when* support will be added, but yes, I do plan on adding it.

That said, I do of course welcome any PRs to help it come along more quickly. :wink:

**Comment by SirMotte** [comment]
This is such a vital module, I'd be glad to see it come to v10 aswell. Thanks for all your hard work.

PS: Please add a way to donate! Little gems like this deserve some coffee!

**Comment by jtracey** [comment]
Quick update on this: I have a dev environment set up, and successfully got the module running to the point that it can detect journal links again. I'm working on fixing identifying the backlinks, and then need to fix rendering them in the right spot. The journal system was revised pretty heavily, but I think it shouldn't take too much more work to get something in a state at least good enough for testing.

**Comment by SirMotte** [comment]
> Quick update on this: I have a dev environment set up, and successfully got the module running to the point that it can detect journal links again. I'm working on fixing identifying the backlinks, and then need to fix rendering them in the right spot. The journal system was revised pretty heavily, but I think it shouldn't take too much more work to get something in a state at least good enough for testing.

Awesome news. Cant wait to dive back into world building again. This is just so good, I don't want to start without the module.

**Comment by SirMotte** [comment]
Hey pal, just wanted to check in, if there has been any progress in v10 compatibility so far. Dearly miss this module :).

**Comment by jtracey** [comment]
Just pushed a commit with v10 support. I would bet that it has some new bugs that I missed, so I'll hold off for ~a week before publishing, and would appreciate any beta testing/PRs. :)

Major changes (I'll write up a full changelog later):

- You can no longer get backlinks on entire Journal Entries, since there's no obvious place to put them. Instead, if you want a backlink, it has to be to a particular Journal Entry Page. Backlinks have been tested with text and image pages so far, but should hopefully work for all page types.
- Default heading has been dropped from `<h1>` to `<h2>`, since otherwise, it gets a bit confusing when using "view multiple pages" mode. The setting still allows you to change it, if you want to bump it back to `<h1>`.
- Only tested with the new UUID-style links (the kind now generated with drag+drop). ID-style links should work but are untested, and I'm guessing name-style links don't currently work; if someone wants those, please file an issue. (See the Foundry [link docs](https://foundryvtt.com/article/journal/#links) if you don't understand what this means.)

**Comment by SirMotte** [comment]
Awesome! I'll test this as soon as I'm home from work.

**Comment by SirMotte** [comment]
> Just pushed a commit with v10 support. I would bet that it has some new bugs that I missed, so I'll hold off for ~a week before publishing, and would appreciate any beta testing/PRs. :)
> 
> Major changes (I'll write up a full changelog later):
> 
>     * You can no longer get backlinks on entire Journal Entries, since there's no obvious place to put them. Instead, if you want a backlink, it has to be to a particular Journal Entry Page. Backlinks have been tested with text and image pages so far, but should hopefully work for all page types.
> 
>     * Default heading has been dropped from `<h1>` to `<h2>`, since otherwise, it gets a bit confusing when using "view multiple pages" mode. The setting still allows you to change it, if you want to bump it back to `<h1>`.
> 
>     * Only tested with the new UUID-style links (the kind now generated with drag+drop). ID-style links should work but are untested, and I'm guessing name-style links don't currently work; if someone wants those, please file an issue. (See the Foundry [link docs](https://foundryvtt.com/article/journal/#links) if you don't understand what this means.)

Alright, gave it a spin just now:

- No Backlinks to entire journals is a bummer, makes linking a little bit more tedious, but can be worked around with. Is there a possibility to have your module add another page to a journal entry to put in those  links?
- No bugs so far. Will have to rework my journals and templates to accomodate the new linking method, but still a very useful module.
- Old ID-Style works for items and actors, not for journals (reason first point)
- Further testing commences tomorrow.

All claims need futher testing, tired from work, my brain might not work reliably enough.

**Comment by jtracey** [comment]
Thanks for testing! :)

>Is there a possibility to have your module add another page to a journal entry to put in those links?

Good question, I'll poke around a bit to see how hard that would be, but won't block a release on it.

**Comment by jtracey** [comment]
New release published on the Foundry package repository. Any bugs or requests should go in their own issues now.
