### ISSUE TITLE
Editing a Journal-Entry can move the Sidebar from the right

### ISSUE THREAD

**Issue by Muwak77** [jtracey/journal-backlinks#15]
When you edit some Journal-Entries and safe them while the module is loaded, the sidebar is moving to the left, leaving a gap to the right. Resizing or Reloading (F5) does not fix this, only reopening foundry by reinserting the URL.

**Comment by Muwak77** [comment]
I did some crude debugging and found that on opening the editor-sheet, the parent of the HTML-object in includelinks() was the document body itself so that the journal-backlinks element was directly added to the body. I did not want to mess with your code too much neither did i find the real reason. But i think exiting the includeLinks() methon when the editmode is opened or the HTML.parent()is pointing to the body would do the trick. 

A really lazy and bad fix i applied was to add:
    $("body > .journal-backlinks").remove();
    to the end of includelinks() so the tags would be removed. But I guess with your knowledge of the code you will figure it out real quick. 
    
Note: this MIGHT be an issue with the investigator-System, I sadly did not have the time to investigate further, but i hope this helps :)

**Comment by jtracey** [comment]
@Muwak77 would you be willing to test #22 to see if that addresses this issue? It should hopefully resolve the underlying problem (modifying the main body, or any other element that doesn't match what we expect) but could break rendering the backlinks at all for other systems that have been getting by with how generous our matching was.

**Comment by Muwak77** [comment]
I'll install it into my TOC and DTE Worlds and see how it goes. Thanks for fixing btw. :)

**Comment by jtracey** [comment]
Should hopefully be fixed in the latest version.
