### ISSUE TITLE
The Sync Now Button does not work properly

### ISSUE THREAD

**Issue by Muwak77** [jtracey/journal-backlinks#16]
![image](https://github.com/jtracey/journal-backlinks/assets/64545711/2db55b5d-353a-4f73-b098-e193327a3e17)

The reason for this is, that Foundry 11 has a default limit in the game.documentIndex.lookup() Method.

Fixed it by changing 

let entries = game.documentIndex.lookup('', {documentTypes: document_types});

to 

let entries = game.documentIndex.lookup('', {documentTypes: document_types,limit:1000000});

maybe you can also 

let entries = game.documentIndex.lookup('', {documentTypes: document_types,limit:0});

does the trick, but again, i hat limited time for testing :)

**Comment by jtracey** [comment]
@Muwak77 thanks for pointing in the right direction. :smiley: There was another problem, but the resolution was fairly similar to your recommendation in #14. Expect a release with a fix soon.
